# Generated by Django 4.0.5 on 2022-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
